apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cloud-native-ecommerce
data:
  SMTP_PORT: '587'
  SMTP_HOST: smtp.gmail.com
  REDIS_URL: redis://34.12.57.218:6379
  KAFKA_BROKER: 34.12.57.218:9092
  KAFKA_EMAIL_TOPIC: email_notifications
  MONGO_URL: mongodb://34.34.92.167:27017
  EMAIL_FROM: mugdhodzs38@gmail.com
  CART_DB_URI: jdbc:postgresql://34.91.172.235:5432/cart_db
  ORDER_DB_URI: jdbc:postgresql://34.91.172.235:5432/order_db
  DB_USERNAME: mugdho
  DB_PASSWORD: admin
  REDIS_HOST: 34.12.57.218
  REDIS_PORT: '6379'
  JWT_ISSUER_URI: http://34.34.92.167:8080/realms/cloud-native-ecommerce
  JWT_SET_URI: http://34.34.92.167:8080/realms/cloud-native-ecommerce/protocol/openid-connect/certs
  API_KEY: secret-api-key
  PORT: '8080'
